---
  team_mappings:
    Benefits Engineering: 0
    Core Payroll Engineering: 10
    Data Science & Engineering: 20
    Growth Engineering: 30
    HR Engineering: 40
    IT: 50
    Payments Engineering: 60
    Platform Engineering: 70
    Risk Engineering: 80
    Security Engineering: 90
    Staff: 110
  specialty_mappings:
  weights:
    days_here: 0.3
    team: 0.9
  min_lunch_group_size: 5
  min_group_score: 0.0001
  time_decay_constant: 80.0
